export const Book = [
    {
      name: "Fantasy",
      image: "genre_fantasy",
      number: 10,
      subGenre: [
        "Alternate History",
        "Children's Story",
        "Comedy",
        "Contemporary",
        "Dark Fantasy",
        "Fairy Tale",
        "Fantasy of Manners",
        "Heroic",
        "High Fantasy",
        "Historical",
        "Low Fantasy",
        "Magical Realism",
        "Mythic",
        "Superhero",
        "Sword and Sorcery",
        "Urban",
        "Young Adult"
      ]
    },
    {
      name: "Horror",
      image: "genre_horror",
      number: 10,
      subGenre: [
        "Body Horror",
        "Comedy",
        "Creepy Kids",
        "Extreme Horror",
        "Gothic",
        "Hauntings",
        "Historical",
        "Lovecraftian",
        "Man-Made",
        "Monsters",
        "Mythic",
        "Occult",
        "Psychic Abilities",
        "Psychological",
        "Quiet Horror",
        "Young Adult"
      ]
    },
    {
      name: "Mystery",
      image: "genre_mystery",
      number: 10,
      subGenre: [
        "Amateur Sleuth",
        "Bumbling Detective",
        "Caper",
        "Child in Peril",
        "Children's Story",
        "Cozy",
        "Culinary",
        "Disabled",
        "Doctor Detective",
        "Furry Sleuth",
        "Hardboiled",
        "Historical",
        "Howdunit",
        "Legal",
        "Locked Room",
        "Multicultural and Diverse",
        "Paranormal",
        "Police Procedural",
        "Private Detective",
        "Whodunit",
        "Woman in Peril",
        "Young Adult"
      ]
    },
    {
      name: "Romance",
      image: "genre_rommance",
      number: 10,
      subGenre: [
        "Billionaires",
        "Comedy",
        "Contemporary",
        "Fantasy Romance",
        "Gothic",
        "Historical",
        "Holidays",
        "Inspirational",
        "Military",
        "Paranormal",
        "Regency",
        "Romantic Suspense",
        "Science Fiction Romance",
        "Sports",
        "Time Travel",
        "Western Romance",
        "Young Adult"
      ]
    },
    {
      name: "Science Fictio",
      image: "genre_fiction",
      number: 10,
      subGenre: [
        "Aliens",
        "Alternate History",
        "Alternate/Parallel Universe",
        "Apocalyptic/Post-Apocalyptic",
        "Biopunk",
        "Children's Story",
        "Colonization",
        "Comedy",
        "Cyberpunk",
        "Dying Earth",
        "Dystopia",
        "Galactic Empire",
        "Generation Ship",
        "Hard Science Fiction",
        "Immortality",
        "Lost Worlds",
        "Military",
        "Mind Transfer",
        "Mundane Science Fiction",
        "Mythic",
        "Nanopunk",
        "Robots/A.I.",
        "Science Fantasy",
        "Science Horror",
        "Slipstream",
        "Soft Science Fiction",
        "Space Exploration",
        "Space Opera",
        "SpyFi",
        "Steampunk",
        "Time Travel",
        "Utopia",
        "Young Adult"
      ]
    },
    {
      name: "Thriller and Suspense",
      image: "genre_thriller",
      number: 10,
      subGenre: [
        "Action",
        "Comedy",
        "Conspiracy",
        "Crime",
        "Disaster",
        "Espionage",
        "Forensic",
        "Historical",
        "Legal",
        "Medical",
        "Military",
        "Mystery Thriller",
        "Paranormal",
        "Political",
        "Psychological",
        "Religious",
        "Technothriller",
        "Young Adult"
      ]
    }, {
      name: "Western",
      image: "genre_fantasy",
      number: 10,
      subGenre: [
        "Bounty Hunters",
        "Cattle Drive",
        "Children's Story",
        "Comedy",
        "Gold Rush",
        "Gunfighters",
        "Land Rush",
        "Lawmen",
        "Mountain Men",
        "Outlaws",
        "Prairie Settlement",
        "Revenge",
        "Wagon Train",
        "Young Adult"
      ]
    }
    // { name: "Comedy", image: "genre_comedy", number: 7 },
    // { name: "Horror", image: "genre_horror", number: 0 },
    // { name: "Thriller", image: "genre_thriller", number: 0 },
    // { name: "Romance", image: "genre_romance", number: 0 },
    // { name: "Action", image: "genre_action", number: 10 },
    // { name: "Drama", image: "genre_drama", number: 0 },
    // { name: "Mystery", image: "genre_mystery", number: 0 },
    // { name: "Fantasy", image: "genre_fantasy", number: 0 },
    // { name: "Adventure", image: "genre_adventure", number: 0 },
    // { name: "Crime", image: "genre_crime", number: 2 },
    // { name: "Animation", image: "genre_animation", number: 0 },
    // { name: "Biography", image: "genre_biography", number: 0 },
    // { name: "History", image: "genre_history", number: 0 },
    // { name: "Family", image: "genre_family", number: 0 },
    // { name: "Sci-FI", image: "genre_sci", number: 5 },
  ];